-----paul andres ---

--- crear una nueva  base de datos

--paso1
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
---paso2
CREATE  USER USUARIO_PRUEVA IDENTIFIED BY "123456"
DEFAULT tablespace "USERS"
TEMPORARY TABLESPACE "TEMP";
--paso3
ALTER USER USUARIO_PRUEVA QUOTA UNLIMITED ON USERS;
--paso4
GRANT CREATE SESSION TO USUARIO_PRUEVA;
---paso5
GRANT "RESOURCE" TO USUARIO_PRUEVA;
----paso+6
ALTER USER USUARIO_PRUEVA DEFAULT ROLE "RESOURCE";


--paso1
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
---paso2
CREATE  USER USUARIO_MATRICULA IDENTIFIED BY "1234567"
DEFAULT tablespace "USERS"
TEMPORARY TABLESPACE "TEMP";
--paso3
ALTER USER USUARIO_MATRICULA QUOTA UNLIMITED ON USERS;
--paso4
GRANT CREATE SESSION TO USUARIO_MATRICULA;
---paso5
GRANT "RESOURCE" TO USUARIO_MATRICULA;
----paso+6
ALTER USER USUARIO_MATRICULA DEFAULT ROLE "RESOURCE";
